[supervisord]
nodaemon=true
user=root

[program:xvfb]
command=/usr/bin/Xvfb :1 -screen 0 1280x720x24
autorestart=true
priority=10

[program:xfce4]
command=/usr/bin/startxfce4
environment=DISPLAY=":1",HOME="/home/zkputer",USER="zkputer"
autorestart=true
priority=20
user=zkputer

[program:x11vnc]
command=/usr/bin/x11vnc -display :1 -nopw -listen localhost -xkb -ncache 10 -ncache_cr -forever
autorestart=true
priority=30

[program:novnc]
command=/opt/novnc/utils/novnc_proxy --vnc localhost:5900 --listen 6080
autorestart=true
priority=40

[program:zkputer-demo]
command=/usr/bin/python3 /home/zkputer/demo.py
environment=HOME="/home/zkputer",USER="zkputer"
autorestart=false
priority=50
user=zkputer
startsecs=5
